# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Astronomy Documentation
email: luke.jagodzinski@gmail.com
baseurl: "/meteor-astronomy" # the subpath of your site, e.g. /blog
url: "http://astronomy.jagi.io" # the base hostname & protocol for your site
v1: "1.2.10"
v2: "2.5.2"
# Build settings
markdown: kramdown
